version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t avatar:latest .
      - docker tag avatar:latest 206896317982.dkr.ecr.us-east-1.amazonaws.com/avatar:latest
  post_build:
    commands:
      - docker push 206896317982.dkr.ecr.us-east-1.amazonaws.com/avatar:latest
      - printf '[{"name":Avatar-Fargate-Task,"imageUri":"%s"}]' 206896317982.dkr.ecr.us-east-1.amazonaws.com/avatar:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
